Add Config Option for CE7 and CSN10 (#31)
mysensors/MySensorsBootloaderRF24 pull request #32
Opened 2018-09-20 16:56 UTC by enny1170

2018-09-21 07:12 UTC, tekka007 commented on MYSBootloader.c
> +//define SPI_PINS_CE9_CSN10
Default configuration should be enabled

2018-09-21 07:12 UTC, tekka007 commented on MYSBootloader.c
> +#define SPI_PINS_CE7_CSN10
Comment this line, see above

2018-09-21 07:13 UTC, tekka007 commented on MYSBootloader.c
> +#define LED_PIN		PB1
Default setting should be used here, you can add PINB5 as comment

2018-09-21 07:14 UTC, tekka007 commented on Makefile
> +CLK = 8000000
Default settings should be used

2018-09-21 07:14 UTC, tekka007 commented on Makefile
> +BAUDRATE = 57600
Default settings should be used, see above

2018-09-21 07:14 UTC, tekka007 requested changes
See comments

2018-09-21 13:12 UTC, enny1170 commented
changes done. please review again

2019-01-15 22:35 UTC, tekka007 approved these changes

2019-01-15 22:35 UTC, merged